video:
  src: '../backflip.mp4'
  show_src: True

window:
  width: 1000
  height: 800
  fps: 60
  background: [0,0,0, 255]
  scale: 30
  x-color: [255,0,0, 255]
  y-color: [0, 255, 255, 255]
  z-color: [0, 255, 0, 255]

camera:
  start: [0,0,-50]
  end: [0,0,0]
  perpendicular: [0,-1,0]
  fov: 90
  
model:
  path: './models/pose_landmarker_full.task'

ragdoll:
  primary-color: WHITE
  secondary-color: BLUE
  connections: [[11,13],[13,15],[12,14],[14,16],[11,12],[24,23],[12,24],[11,23],[24,26],[23,25],[25,27],[26,28]]
